version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  #Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
