require("atro.utils.logs"):init()
LOGGER:info("Loading configuration")
require("atro.config"):init_default()
require("atro.config"):init_user(os.getenv("HOME") .. "/.config/nvim-custom")
require("atro.lazy")
