---
name: Test
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  pull_request:
    branches: ["main"]
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run pre-commit hooks and tests
        run: devenv test
