---
name: Pre-commit
on:
    workflow_dispatch: # allows manual triggering
    pull_request:
        branches: [main]
    push:
        branches:
            - main
jobs:
    pre-commit:
        name: Run pre-commit hooks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pre-commit/action@v3.0.1
              with:
                  extra_args: --all-files
